// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dd/dd.proto

package dd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// COMMON
type GetByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIdRequest) Reset()         { *m = GetByIdRequest{} }
func (m *GetByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetByIdRequest) ProtoMessage()    {}
func (*GetByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{0}
}
func (m *GetByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIdRequest.Unmarshal(m, b)
}
func (m *GetByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIdRequest.Marshal(b, m, deterministic)
}
func (dst *GetByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIdRequest.Merge(dst, src)
}
func (m *GetByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetByIdRequest.Size(m)
}
func (m *GetByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIdRequest proto.InternalMessageInfo

func (m *GetByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SearchParams struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchParams) Reset()         { *m = SearchParams{} }
func (m *SearchParams) String() string { return proto.CompactTextString(m) }
func (*SearchParams) ProtoMessage()    {}
func (*SearchParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{1}
}
func (m *SearchParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchParams.Unmarshal(m, b)
}
func (m *SearchParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchParams.Marshal(b, m, deterministic)
}
func (dst *SearchParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchParams.Merge(dst, src)
}
func (m *SearchParams) XXX_Size() int {
	return xxx_messageInfo_SearchParams.Size(m)
}
func (m *SearchParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchParams.DiscardUnknown(m)
}

var xxx_messageInfo_SearchParams proto.InternalMessageInfo

func (m *SearchParams) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *SearchParams) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchParams) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Blank struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blank) Reset()         { *m = Blank{} }
func (m *Blank) String() string { return proto.CompactTextString(m) }
func (*Blank) ProtoMessage()    {}
func (*Blank) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{2}
}
func (m *Blank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blank.Unmarshal(m, b)
}
func (m *Blank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blank.Marshal(b, m, deterministic)
}
func (dst *Blank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blank.Merge(dst, src)
}
func (m *Blank) XXX_Size() int {
	return xxx_messageInfo_Blank.Size(m)
}
func (m *Blank) XXX_DiscardUnknown() {
	xxx_messageInfo_Blank.DiscardUnknown(m)
}

var xxx_messageInfo_Blank proto.InternalMessageInfo

// AUTH
type AuthRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{3}
}
func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (dst *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(dst, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ReigstrationRequired bool     `protobuf:"varint,2,opt,name=reigstrationRequired,proto3" json:"reigstrationRequired,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{4}
}
func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (dst *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(dst, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AuthResponse) GetReigstrationRequired() bool {
	if m != nil {
		return m.ReigstrationRequired
	}
	return false
}

type CreateUserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{5}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// *************************************
//              CAMPAIGNS
// *************************************
type GetCampaignsRequest struct {
	Search               *SearchParams `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetCampaignsRequest) Reset()         { *m = GetCampaignsRequest{} }
func (m *GetCampaignsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCampaignsRequest) ProtoMessage()    {}
func (*GetCampaignsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{6}
}
func (m *GetCampaignsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCampaignsRequest.Unmarshal(m, b)
}
func (m *GetCampaignsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCampaignsRequest.Marshal(b, m, deterministic)
}
func (dst *GetCampaignsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCampaignsRequest.Merge(dst, src)
}
func (m *GetCampaignsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCampaignsRequest.Size(m)
}
func (m *GetCampaignsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCampaignsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCampaignsRequest proto.InternalMessageInfo

func (m *GetCampaignsRequest) GetSearch() *SearchParams {
	if m != nil {
		return m.Search
	}
	return nil
}

type GetCampaignsResponse struct {
	Campaigns            []*CampaignCore `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	Total                uint32          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetCampaignsResponse) Reset()         { *m = GetCampaignsResponse{} }
func (m *GetCampaignsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCampaignsResponse) ProtoMessage()    {}
func (*GetCampaignsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{7}
}
func (m *GetCampaignsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCampaignsResponse.Unmarshal(m, b)
}
func (m *GetCampaignsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCampaignsResponse.Marshal(b, m, deterministic)
}
func (dst *GetCampaignsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCampaignsResponse.Merge(dst, src)
}
func (m *GetCampaignsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCampaignsResponse.Size(m)
}
func (m *GetCampaignsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCampaignsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCampaignsResponse proto.InternalMessageInfo

func (m *GetCampaignsResponse) GetCampaigns() []*CampaignCore {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

func (m *GetCampaignsResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CreateCampaignRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCampaignRequest) Reset()         { *m = CreateCampaignRequest{} }
func (m *CreateCampaignRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCampaignRequest) ProtoMessage()    {}
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{8}
}
func (m *CreateCampaignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCampaignRequest.Unmarshal(m, b)
}
func (m *CreateCampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCampaignRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCampaignRequest.Merge(dst, src)
}
func (m *CreateCampaignRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCampaignRequest.Size(m)
}
func (m *CreateCampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCampaignRequest proto.InternalMessageInfo

type CreateCampaignResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCampaignResponse) Reset()         { *m = CreateCampaignResponse{} }
func (m *CreateCampaignResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCampaignResponse) ProtoMessage()    {}
func (*CreateCampaignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{9}
}
func (m *CreateCampaignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCampaignResponse.Unmarshal(m, b)
}
func (m *CreateCampaignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCampaignResponse.Marshal(b, m, deterministic)
}
func (dst *CreateCampaignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCampaignResponse.Merge(dst, src)
}
func (m *CreateCampaignResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCampaignResponse.Size(m)
}
func (m *CreateCampaignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCampaignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCampaignResponse proto.InternalMessageInfo

func (m *CreateCampaignResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EditCampaignRequest struct {
	Campaign             *CampaignCore `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	Id                   string        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EditCampaignRequest) Reset()         { *m = EditCampaignRequest{} }
func (m *EditCampaignRequest) String() string { return proto.CompactTextString(m) }
func (*EditCampaignRequest) ProtoMessage()    {}
func (*EditCampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{10}
}
func (m *EditCampaignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditCampaignRequest.Unmarshal(m, b)
}
func (m *EditCampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditCampaignRequest.Marshal(b, m, deterministic)
}
func (dst *EditCampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditCampaignRequest.Merge(dst, src)
}
func (m *EditCampaignRequest) XXX_Size() int {
	return xxx_messageInfo_EditCampaignRequest.Size(m)
}
func (m *EditCampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditCampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditCampaignRequest proto.InternalMessageInfo

func (m *EditCampaignRequest) GetCampaign() *CampaignCore {
	if m != nil {
		return m.Campaign
	}
	return nil
}

func (m *EditCampaignRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateEntityPresetResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEntityPresetResponse) Reset()         { *m = CreateEntityPresetResponse{} }
func (m *CreateEntityPresetResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEntityPresetResponse) ProtoMessage()    {}
func (*CreateEntityPresetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{11}
}
func (m *CreateEntityPresetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntityPresetResponse.Unmarshal(m, b)
}
func (m *CreateEntityPresetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntityPresetResponse.Marshal(b, m, deterministic)
}
func (dst *CreateEntityPresetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntityPresetResponse.Merge(dst, src)
}
func (m *CreateEntityPresetResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEntityPresetResponse.Size(m)
}
func (m *CreateEntityPresetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntityPresetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntityPresetResponse proto.InternalMessageInfo

func (m *CreateEntityPresetResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EditEntityPresetRequest struct {
	CampaignId           string        `protobuf:"bytes,1,opt,name=campaignId,proto3" json:"campaignId,omitempty"`
	Id                   string        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Preset               *EntityPreset `protobuf:"bytes,3,opt,name=preset,proto3" json:"preset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EditEntityPresetRequest) Reset()         { *m = EditEntityPresetRequest{} }
func (m *EditEntityPresetRequest) String() string { return proto.CompactTextString(m) }
func (*EditEntityPresetRequest) ProtoMessage()    {}
func (*EditEntityPresetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{12}
}
func (m *EditEntityPresetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditEntityPresetRequest.Unmarshal(m, b)
}
func (m *EditEntityPresetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditEntityPresetRequest.Marshal(b, m, deterministic)
}
func (dst *EditEntityPresetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditEntityPresetRequest.Merge(dst, src)
}
func (m *EditEntityPresetRequest) XXX_Size() int {
	return xxx_messageInfo_EditEntityPresetRequest.Size(m)
}
func (m *EditEntityPresetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditEntityPresetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditEntityPresetRequest proto.InternalMessageInfo

func (m *EditEntityPresetRequest) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

func (m *EditEntityPresetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EditEntityPresetRequest) GetPreset() *EntityPreset {
	if m != nil {
		return m.Preset
	}
	return nil
}

type GetQuestsRequest struct {
	Search               *SearchParams `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetQuestsRequest) Reset()         { *m = GetQuestsRequest{} }
func (m *GetQuestsRequest) String() string { return proto.CompactTextString(m) }
func (*GetQuestsRequest) ProtoMessage()    {}
func (*GetQuestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{13}
}
func (m *GetQuestsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuestsRequest.Unmarshal(m, b)
}
func (m *GetQuestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuestsRequest.Marshal(b, m, deterministic)
}
func (dst *GetQuestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuestsRequest.Merge(dst, src)
}
func (m *GetQuestsRequest) XXX_Size() int {
	return xxx_messageInfo_GetQuestsRequest.Size(m)
}
func (m *GetQuestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuestsRequest proto.InternalMessageInfo

func (m *GetQuestsRequest) GetSearch() *SearchParams {
	if m != nil {
		return m.Search
	}
	return nil
}

type GetQuestsResponse struct {
	Quests               []*Quest `protobuf:"bytes,1,rep,name=quests,proto3" json:"quests,omitempty"`
	Total                uint32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuestsResponse) Reset()         { *m = GetQuestsResponse{} }
func (m *GetQuestsResponse) String() string { return proto.CompactTextString(m) }
func (*GetQuestsResponse) ProtoMessage()    {}
func (*GetQuestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{14}
}
func (m *GetQuestsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuestsResponse.Unmarshal(m, b)
}
func (m *GetQuestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuestsResponse.Marshal(b, m, deterministic)
}
func (dst *GetQuestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuestsResponse.Merge(dst, src)
}
func (m *GetQuestsResponse) XXX_Size() int {
	return xxx_messageInfo_GetQuestsResponse.Size(m)
}
func (m *GetQuestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuestsResponse proto.InternalMessageInfo

func (m *GetQuestsResponse) GetQuests() []*Quest {
	if m != nil {
		return m.Quests
	}
	return nil
}

func (m *GetQuestsResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CreateQuestRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateQuestRequest) Reset()         { *m = CreateQuestRequest{} }
func (m *CreateQuestRequest) String() string { return proto.CompactTextString(m) }
func (*CreateQuestRequest) ProtoMessage()    {}
func (*CreateQuestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{15}
}
func (m *CreateQuestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQuestRequest.Unmarshal(m, b)
}
func (m *CreateQuestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQuestRequest.Marshal(b, m, deterministic)
}
func (dst *CreateQuestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQuestRequest.Merge(dst, src)
}
func (m *CreateQuestRequest) XXX_Size() int {
	return xxx_messageInfo_CreateQuestRequest.Size(m)
}
func (m *CreateQuestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQuestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQuestRequest proto.InternalMessageInfo

type CreateQuestResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateQuestResponse) Reset()         { *m = CreateQuestResponse{} }
func (m *CreateQuestResponse) String() string { return proto.CompactTextString(m) }
func (*CreateQuestResponse) ProtoMessage()    {}
func (*CreateQuestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{16}
}
func (m *CreateQuestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQuestResponse.Unmarshal(m, b)
}
func (m *CreateQuestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQuestResponse.Marshal(b, m, deterministic)
}
func (dst *CreateQuestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQuestResponse.Merge(dst, src)
}
func (m *CreateQuestResponse) XXX_Size() int {
	return xxx_messageInfo_CreateQuestResponse.Size(m)
}
func (m *CreateQuestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQuestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQuestResponse proto.InternalMessageInfo

func (m *CreateQuestResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EditQuestRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quest                *Quest   `protobuf:"bytes,2,opt,name=quest,proto3" json:"quest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditQuestRequest) Reset()         { *m = EditQuestRequest{} }
func (m *EditQuestRequest) String() string { return proto.CompactTextString(m) }
func (*EditQuestRequest) ProtoMessage()    {}
func (*EditQuestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{17}
}
func (m *EditQuestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditQuestRequest.Unmarshal(m, b)
}
func (m *EditQuestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditQuestRequest.Marshal(b, m, deterministic)
}
func (dst *EditQuestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditQuestRequest.Merge(dst, src)
}
func (m *EditQuestRequest) XXX_Size() int {
	return xxx_messageInfo_EditQuestRequest.Size(m)
}
func (m *EditQuestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditQuestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditQuestRequest proto.InternalMessageInfo

func (m *EditQuestRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EditQuestRequest) GetQuest() *Quest {
	if m != nil {
		return m.Quest
	}
	return nil
}

type Quest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quest) Reset()         { *m = Quest{} }
func (m *Quest) String() string { return proto.CompactTextString(m) }
func (*Quest) ProtoMessage()    {}
func (*Quest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{18}
}
func (m *Quest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quest.Unmarshal(m, b)
}
func (m *Quest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quest.Marshal(b, m, deterministic)
}
func (dst *Quest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quest.Merge(dst, src)
}
func (m *Quest) XXX_Size() int {
	return xxx_messageInfo_Quest.Size(m)
}
func (m *Quest) XXX_DiscardUnknown() {
	xxx_messageInfo_Quest.DiscardUnknown(m)
}

var xxx_messageInfo_Quest proto.InternalMessageInfo

func (m *Quest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Quest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Quest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageURL             string   `protobuf:"bytes,3,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	CreatedAt            uint64   `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{19}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

func (m *User) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type CampaignCore struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageId              string   `protobuf:"bytes,4,opt,name=imageId,proto3" json:"imageId,omitempty"`
	ExperienceTable      []int64  `protobuf:"varint,10,rep,packed,name=experienceTable,proto3" json:"experienceTable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CampaignCore) Reset()         { *m = CampaignCore{} }
func (m *CampaignCore) String() string { return proto.CompactTextString(m) }
func (*CampaignCore) ProtoMessage()    {}
func (*CampaignCore) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{20}
}
func (m *CampaignCore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignCore.Unmarshal(m, b)
}
func (m *CampaignCore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignCore.Marshal(b, m, deterministic)
}
func (dst *CampaignCore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignCore.Merge(dst, src)
}
func (m *CampaignCore) XXX_Size() int {
	return xxx_messageInfo_CampaignCore.Size(m)
}
func (m *CampaignCore) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignCore.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignCore proto.InternalMessageInfo

func (m *CampaignCore) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CampaignCore) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CampaignCore) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CampaignCore) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *CampaignCore) GetExperienceTable() []int64 {
	if m != nil {
		return m.ExperienceTable
	}
	return nil
}

type Campaign struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageId              string          `protobuf:"bytes,4,opt,name=imageId,proto3" json:"imageId,omitempty"`
	ExperienceTable      []int64         `protobuf:"varint,10,rep,packed,name=experienceTable,proto3" json:"experienceTable,omitempty"`
	Users                []*CampaignUser `protobuf:"bytes,11,rep,name=users,proto3" json:"users,omitempty"`
	Items                []*Item         `protobuf:"bytes,12,rep,name=items,proto3" json:"items,omitempty"`
	EntityPresets        []*EntityPreset `protobuf:"bytes,13,rep,name=entityPresets,proto3" json:"entityPresets,omitempty"`
	Entities             []*Entity       `protobuf:"bytes,14,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Campaign) Reset()         { *m = Campaign{} }
func (m *Campaign) String() string { return proto.CompactTextString(m) }
func (*Campaign) ProtoMessage()    {}
func (*Campaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{21}
}
func (m *Campaign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Campaign.Unmarshal(m, b)
}
func (m *Campaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Campaign.Marshal(b, m, deterministic)
}
func (dst *Campaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Campaign.Merge(dst, src)
}
func (m *Campaign) XXX_Size() int {
	return xxx_messageInfo_Campaign.Size(m)
}
func (m *Campaign) XXX_DiscardUnknown() {
	xxx_messageInfo_Campaign.DiscardUnknown(m)
}

var xxx_messageInfo_Campaign proto.InternalMessageInfo

func (m *Campaign) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Campaign) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Campaign) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Campaign) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *Campaign) GetExperienceTable() []int64 {
	if m != nil {
		return m.ExperienceTable
	}
	return nil
}

func (m *Campaign) GetUsers() []*CampaignUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Campaign) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Campaign) GetEntityPresets() []*EntityPreset {
	if m != nil {
		return m.EntityPresets
	}
	return nil
}

func (m *Campaign) GetEntities() []*Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

type Entity struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	User                 *User         `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	ImageId              string        `protobuf:"bytes,5,opt,name=imageId,proto3" json:"imageId,omitempty"`
	Attributes           []*Attribute  `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Xp                   int64         `protobuf:"varint,7,opt,name=xp,proto3" json:"xp,omitempty"`
	Inventory            *Inventory    `protobuf:"bytes,8,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Health               *Health       `protobuf:"bytes,9,opt,name=health,proto3" json:"health,omitempty"`
	Preset               *EntityPreset `protobuf:"bytes,10,opt,name=preset,proto3" json:"preset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{22}
}
func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (dst *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(dst, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Entity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Entity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Entity) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Entity) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *Entity) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Entity) GetXp() int64 {
	if m != nil {
		return m.Xp
	}
	return 0
}

func (m *Entity) GetInventory() *Inventory {
	if m != nil {
		return m.Inventory
	}
	return nil
}

func (m *Entity) GetHealth() *Health {
	if m != nil {
		return m.Health
	}
	return nil
}

func (m *Entity) GetPreset() *EntityPreset {
	if m != nil {
		return m.Preset
	}
	return nil
}

type EntityPreset struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string             `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	User                 *User              `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	ImageId              string             `protobuf:"bytes,5,opt,name=imageId,proto3" json:"imageId,omitempty"`
	Attributes           []*EntityAttribute `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Inventory            *Inventory         `protobuf:"bytes,7,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Health               *HealthPreset      `protobuf:"bytes,8,opt,name=health,proto3" json:"health,omitempty"`
	PlayerCreatable      bool               `protobuf:"varint,9,opt,name=playerCreatable,proto3" json:"playerCreatable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EntityPreset) Reset()         { *m = EntityPreset{} }
func (m *EntityPreset) String() string { return proto.CompactTextString(m) }
func (*EntityPreset) ProtoMessage()    {}
func (*EntityPreset) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{23}
}
func (m *EntityPreset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityPreset.Unmarshal(m, b)
}
func (m *EntityPreset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityPreset.Marshal(b, m, deterministic)
}
func (dst *EntityPreset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityPreset.Merge(dst, src)
}
func (m *EntityPreset) XXX_Size() int {
	return xxx_messageInfo_EntityPreset.Size(m)
}
func (m *EntityPreset) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityPreset.DiscardUnknown(m)
}

var xxx_messageInfo_EntityPreset proto.InternalMessageInfo

func (m *EntityPreset) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EntityPreset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EntityPreset) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EntityPreset) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *EntityPreset) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *EntityPreset) GetAttributes() []*EntityAttribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *EntityPreset) GetInventory() *Inventory {
	if m != nil {
		return m.Inventory
	}
	return nil
}

func (m *EntityPreset) GetHealth() *HealthPreset {
	if m != nil {
		return m.Health
	}
	return nil
}

func (m *EntityPreset) GetPlayerCreatable() bool {
	if m != nil {
		return m.PlayerCreatable
	}
	return false
}

type EntityAttribute struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ImageId              string   `protobuf:"bytes,3,opt,name=imageId,proto3" json:"imageId,omitempty"`
	DefaultValue         string   `protobuf:"bytes,4,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
	Type                 int32    `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Options              []string `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	Class                int32    `protobuf:"varint,7,opt,name=class,proto3" json:"class,omitempty"`
	Required             bool     `protobuf:"varint,8,opt,name=required,proto3" json:"required,omitempty"`
	Max                  int64    `protobuf:"varint,9,opt,name=max,proto3" json:"max,omitempty"`
	Min                  int64    `protobuf:"varint,10,opt,name=min,proto3" json:"min,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityAttribute) Reset()         { *m = EntityAttribute{} }
func (m *EntityAttribute) String() string { return proto.CompactTextString(m) }
func (*EntityAttribute) ProtoMessage()    {}
func (*EntityAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{24}
}
func (m *EntityAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityAttribute.Unmarshal(m, b)
}
func (m *EntityAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityAttribute.Marshal(b, m, deterministic)
}
func (dst *EntityAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityAttribute.Merge(dst, src)
}
func (m *EntityAttribute) XXX_Size() int {
	return xxx_messageInfo_EntityAttribute.Size(m)
}
func (m *EntityAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_EntityAttribute proto.InternalMessageInfo

func (m *EntityAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EntityAttribute) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EntityAttribute) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *EntityAttribute) GetDefaultValue() string {
	if m != nil {
		return m.DefaultValue
	}
	return ""
}

func (m *EntityAttribute) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *EntityAttribute) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *EntityAttribute) GetClass() int32 {
	if m != nil {
		return m.Class
	}
	return 0
}

func (m *EntityAttribute) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *EntityAttribute) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *EntityAttribute) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

type Item struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageId              string       `protobuf:"bytes,4,opt,name=imageId,proto3" json:"imageId,omitempty"`
	Attributes           []*Attribute `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{25}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *Item) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Inventory struct {
	Items                []*InventoryItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Inventory) Reset()         { *m = Inventory{} }
func (m *Inventory) String() string { return proto.CompactTextString(m) }
func (*Inventory) ProtoMessage()    {}
func (*Inventory) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{26}
}
func (m *Inventory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inventory.Unmarshal(m, b)
}
func (m *Inventory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inventory.Marshal(b, m, deterministic)
}
func (dst *Inventory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inventory.Merge(dst, src)
}
func (m *Inventory) XXX_Size() int {
	return xxx_messageInfo_Inventory.Size(m)
}
func (m *Inventory) XXX_DiscardUnknown() {
	xxx_messageInfo_Inventory.DiscardUnknown(m)
}

var xxx_messageInfo_Inventory proto.InternalMessageInfo

func (m *Inventory) GetItems() []*InventoryItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type InventoryItem struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InventoryItem) Reset()         { *m = InventoryItem{} }
func (m *InventoryItem) String() string { return proto.CompactTextString(m) }
func (*InventoryItem) ProtoMessage()    {}
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{27}
}
func (m *InventoryItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryItem.Unmarshal(m, b)
}
func (m *InventoryItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryItem.Marshal(b, m, deterministic)
}
func (dst *InventoryItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryItem.Merge(dst, src)
}
func (m *InventoryItem) XXX_Size() int {
	return xxx_messageInfo_InventoryItem.Size(m)
}
func (m *InventoryItem) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryItem.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryItem proto.InternalMessageInfo

func (m *InventoryItem) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *InventoryItem) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type Attribute struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{28}
}
func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (dst *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(dst, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attribute) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Attribute) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type CampaignUser struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	IsAdmin              bool     `protobuf:"varint,2,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CampaignUser) Reset()         { *m = CampaignUser{} }
func (m *CampaignUser) String() string { return proto.CompactTextString(m) }
func (*CampaignUser) ProtoMessage()    {}
func (*CampaignUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{29}
}
func (m *CampaignUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignUser.Unmarshal(m, b)
}
func (m *CampaignUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignUser.Marshal(b, m, deterministic)
}
func (dst *CampaignUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignUser.Merge(dst, src)
}
func (m *CampaignUser) XXX_Size() int {
	return xxx_messageInfo_CampaignUser.Size(m)
}
func (m *CampaignUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignUser.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignUser proto.InternalMessageInfo

func (m *CampaignUser) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CampaignUser) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type HealthPreset struct {
	Mode                 int32    `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Max                  int64    `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthPreset) Reset()         { *m = HealthPreset{} }
func (m *HealthPreset) String() string { return proto.CompactTextString(m) }
func (*HealthPreset) ProtoMessage()    {}
func (*HealthPreset) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{30}
}
func (m *HealthPreset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthPreset.Unmarshal(m, b)
}
func (m *HealthPreset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthPreset.Marshal(b, m, deterministic)
}
func (dst *HealthPreset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthPreset.Merge(dst, src)
}
func (m *HealthPreset) XXX_Size() int {
	return xxx_messageInfo_HealthPreset.Size(m)
}
func (m *HealthPreset) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthPreset.DiscardUnknown(m)
}

var xxx_messageInfo_HealthPreset proto.InternalMessageInfo

func (m *HealthPreset) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *HealthPreset) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

type Health struct {
	Mode                 int32            `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Normal               *Health_Normal   `protobuf:"bytes,2,opt,name=normal,proto3" json:"normal,omitempty"`
	MultiBar             *Health_MultiBar `protobuf:"bytes,3,opt,name=multiBar,proto3" json:"multiBar,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Health) Reset()         { *m = Health{} }
func (m *Health) String() string { return proto.CompactTextString(m) }
func (*Health) ProtoMessage()    {}
func (*Health) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{31}
}
func (m *Health) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Health.Unmarshal(m, b)
}
func (m *Health) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Health.Marshal(b, m, deterministic)
}
func (dst *Health) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Health.Merge(dst, src)
}
func (m *Health) XXX_Size() int {
	return xxx_messageInfo_Health.Size(m)
}
func (m *Health) XXX_DiscardUnknown() {
	xxx_messageInfo_Health.DiscardUnknown(m)
}

var xxx_messageInfo_Health proto.InternalMessageInfo

func (m *Health) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *Health) GetNormal() *Health_Normal {
	if m != nil {
		return m.Normal
	}
	return nil
}

func (m *Health) GetMultiBar() *Health_MultiBar {
	if m != nil {
		return m.MultiBar
	}
	return nil
}

type Health_Normal struct {
	Max                  int64    `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	Current              int64    `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	Temp                 int64    `protobuf:"varint,3,opt,name=temp,proto3" json:"temp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Health_Normal) Reset()         { *m = Health_Normal{} }
func (m *Health_Normal) String() string { return proto.CompactTextString(m) }
func (*Health_Normal) ProtoMessage()    {}
func (*Health_Normal) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{31, 0}
}
func (m *Health_Normal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Health_Normal.Unmarshal(m, b)
}
func (m *Health_Normal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Health_Normal.Marshal(b, m, deterministic)
}
func (dst *Health_Normal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Health_Normal.Merge(dst, src)
}
func (m *Health_Normal) XXX_Size() int {
	return xxx_messageInfo_Health_Normal.Size(m)
}
func (m *Health_Normal) XXX_DiscardUnknown() {
	xxx_messageInfo_Health_Normal.DiscardUnknown(m)
}

var xxx_messageInfo_Health_Normal proto.InternalMessageInfo

func (m *Health_Normal) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *Health_Normal) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *Health_Normal) GetTemp() int64 {
	if m != nil {
		return m.Temp
	}
	return 0
}

type Health_MultiBar struct {
	Bars                 []int64  `protobuf:"varint,1,rep,packed,name=bars,proto3" json:"bars,omitempty"`
	Current              int64    `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Health_MultiBar) Reset()         { *m = Health_MultiBar{} }
func (m *Health_MultiBar) String() string { return proto.CompactTextString(m) }
func (*Health_MultiBar) ProtoMessage()    {}
func (*Health_MultiBar) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_40e3a8bc0e11b39a, []int{31, 1}
}
func (m *Health_MultiBar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Health_MultiBar.Unmarshal(m, b)
}
func (m *Health_MultiBar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Health_MultiBar.Marshal(b, m, deterministic)
}
func (dst *Health_MultiBar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Health_MultiBar.Merge(dst, src)
}
func (m *Health_MultiBar) XXX_Size() int {
	return xxx_messageInfo_Health_MultiBar.Size(m)
}
func (m *Health_MultiBar) XXX_DiscardUnknown() {
	xxx_messageInfo_Health_MultiBar.DiscardUnknown(m)
}

var xxx_messageInfo_Health_MultiBar proto.InternalMessageInfo

func (m *Health_MultiBar) GetBars() []int64 {
	if m != nil {
		return m.Bars
	}
	return nil
}

func (m *Health_MultiBar) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func init() {
	proto.RegisterType((*GetByIdRequest)(nil), "dd.GetByIdRequest")
	proto.RegisterType((*SearchParams)(nil), "dd.SearchParams")
	proto.RegisterType((*Blank)(nil), "dd.Blank")
	proto.RegisterType((*AuthRequest)(nil), "dd.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "dd.AuthResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "dd.CreateUserRequest")
	proto.RegisterType((*GetCampaignsRequest)(nil), "dd.GetCampaignsRequest")
	proto.RegisterType((*GetCampaignsResponse)(nil), "dd.GetCampaignsResponse")
	proto.RegisterType((*CreateCampaignRequest)(nil), "dd.CreateCampaignRequest")
	proto.RegisterType((*CreateCampaignResponse)(nil), "dd.CreateCampaignResponse")
	proto.RegisterType((*EditCampaignRequest)(nil), "dd.EditCampaignRequest")
	proto.RegisterType((*CreateEntityPresetResponse)(nil), "dd.CreateEntityPresetResponse")
	proto.RegisterType((*EditEntityPresetRequest)(nil), "dd.EditEntityPresetRequest")
	proto.RegisterType((*GetQuestsRequest)(nil), "dd.GetQuestsRequest")
	proto.RegisterType((*GetQuestsResponse)(nil), "dd.GetQuestsResponse")
	proto.RegisterType((*CreateQuestRequest)(nil), "dd.CreateQuestRequest")
	proto.RegisterType((*CreateQuestResponse)(nil), "dd.CreateQuestResponse")
	proto.RegisterType((*EditQuestRequest)(nil), "dd.EditQuestRequest")
	proto.RegisterType((*Quest)(nil), "dd.Quest")
	proto.RegisterType((*User)(nil), "dd.User")
	proto.RegisterType((*CampaignCore)(nil), "dd.CampaignCore")
	proto.RegisterType((*Campaign)(nil), "dd.Campaign")
	proto.RegisterType((*Entity)(nil), "dd.Entity")
	proto.RegisterType((*EntityPreset)(nil), "dd.EntityPreset")
	proto.RegisterType((*EntityAttribute)(nil), "dd.EntityAttribute")
	proto.RegisterType((*Item)(nil), "dd.Item")
	proto.RegisterType((*Inventory)(nil), "dd.Inventory")
	proto.RegisterType((*InventoryItem)(nil), "dd.InventoryItem")
	proto.RegisterType((*Attribute)(nil), "dd.Attribute")
	proto.RegisterType((*CampaignUser)(nil), "dd.CampaignUser")
	proto.RegisterType((*HealthPreset)(nil), "dd.HealthPreset")
	proto.RegisterType((*Health)(nil), "dd.Health")
	proto.RegisterType((*Health_Normal)(nil), "dd.Health.Normal")
	proto.RegisterType((*Health_MultiBar)(nil), "dd.Health.MultiBar")
}

func init() { proto.RegisterFile("dd/dd.proto", fileDescriptor_dd_40e3a8bc0e11b39a) }

var fileDescriptor_dd_40e3a8bc0e11b39a = []byte{
	// 1354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0xd6, 0x7a, 0x7f, 0x62, 0x9f, 0xdd, 0xfc, 0x74, 0x92, 0x36, 0xae, 0xa9, 0xca, 0x32, 0x88,
	0x76, 0x2b, 0xda, 0x54, 0x6a, 0x2b, 0x28, 0x12, 0xa2, 0x4a, 0xd2, 0xb2, 0x5d, 0xa9, 0xad, 0xda,
	0x29, 0xe5, 0x02, 0x71, 0x81, 0xb3, 0x9e, 0x36, 0x56, 0xd7, 0xde, 0xad, 0x3d, 0x8b, 0x92, 0x47,
	0xe0, 0x01, 0x90, 0x78, 0x06, 0x9e, 0x81, 0x0b, 0xc4, 0x73, 0x71, 0x81, 0xe6, 0xcc, 0x8c, 0x3d,
	0x76, 0x9c, 0x04, 0xa1, 0x22, 0xb8, 0xf3, 0x9c, 0xdf, 0x6f, 0xbe, 0xf9, 0x3b, 0xc7, 0xd0, 0x8f,
	0xa2, 0xdb, 0x51, 0xb4, 0xb3, 0xc8, 0xe6, 0x62, 0x4e, 0x9c, 0x28, 0xa2, 0x43, 0x58, 0x1b, 0x73,
	0xb1, 0x77, 0x3c, 0x89, 0x18, 0x7f, 0xb7, 0xe4, 0xb9, 0x20, 0x6b, 0xe0, 0xc4, 0x91, 0xdf, 0x1a,
	0xb6, 0x46, 0x1e, 0x73, 0xe2, 0x88, 0x3e, 0x83, 0xc1, 0x4b, 0x1e, 0x66, 0xd3, 0xc3, 0xe7, 0x61,
	0x16, 0x26, 0x39, 0xd9, 0x80, 0x76, 0x1c, 0xe5, 0x7e, 0x6b, 0xd8, 0x1e, 0x79, 0x4c, 0x7e, 0x92,
	0x2d, 0xe8, 0xce, 0xe2, 0x24, 0x16, 0xbe, 0x33, 0x6c, 0x8d, 0x56, 0x99, 0x1a, 0x90, 0x4b, 0xd0,
	0x9b, 0xbf, 0x7e, 0x9d, 0x73, 0xe1, 0xb7, 0x51, 0xac, 0x47, 0x74, 0x05, 0xba, 0x7b, 0xb3, 0x30,
	0x7d, 0x4b, 0x3f, 0x86, 0xfe, 0xee, 0x52, 0x1c, 0x9a, 0xbc, 0x5b, 0xd0, 0x15, 0xf3, 0xb7, 0x3c,
	0xd5, 0xa9, 0xd5, 0x80, 0xfe, 0x00, 0x03, 0x65, 0x94, 0x2f, 0xe6, 0x69, 0xce, 0xc9, 0x15, 0xe8,
	0x2c, 0x73, 0x9e, 0xa1, 0x51, 0xff, 0x8e, 0xbb, 0x13, 0x45, 0x3b, 0xaf, 0x72, 0x9e, 0x31, 0x94,
	0x92, 0x3b, 0xb0, 0x95, 0xf1, 0xf8, 0x4d, 0x2e, 0xb2, 0x50, 0xc4, 0xf3, 0x54, 0x86, 0x8e, 0x33,
	0x1e, 0x21, 0x30, 0x97, 0x35, 0xea, 0xe8, 0x23, 0xb8, 0xb0, 0x9f, 0xf1, 0x50, 0x70, 0x8c, 0x73,
	0x16, 0x18, 0x12, 0x80, 0x2b, 0xd3, 0xa4, 0x61, 0xc2, 0x31, 0xa4, 0xc7, 0x8a, 0x31, 0x7d, 0x00,
	0x9b, 0x63, 0x2e, 0xf6, 0xc3, 0x64, 0x11, 0xc6, 0x6f, 0xd2, 0xdc, 0x04, 0x1a, 0x41, 0x2f, 0x47,
	0xf6, 0x34, 0xe2, 0x0d, 0x89, 0xd8, 0xe6, 0x93, 0x69, 0x3d, 0xfd, 0x1e, 0xb6, 0xaa, 0x01, 0xf4,
	0x8c, 0x77, 0xc0, 0x9b, 0x1a, 0x21, 0xb2, 0xae, 0x83, 0x18, 0xcb, 0xfd, 0x79, 0xc6, 0x59, 0x69,
	0xa2, 0xa0, 0x8b, 0x70, 0x66, 0x56, 0x03, 0x07, 0x74, 0x1b, 0x2e, 0xaa, 0x59, 0x1a, 0x37, 0x0d,
	0x90, 0x8e, 0xe0, 0x52, 0x5d, 0xa1, 0x13, 0xd7, 0x37, 0xc2, 0x4b, 0xd8, 0x7c, 0x14, 0xc5, 0xa2,
	0x16, 0x80, 0xdc, 0x04, 0xd7, 0x24, 0xb7, 0xe7, 0x58, 0x81, 0x57, 0x58, 0xe8, 0xa0, 0x4e, 0x11,
	0xf4, 0x26, 0x04, 0x2a, 0xfd, 0xa3, 0x54, 0xc4, 0xe2, 0xf8, 0x79, 0xc6, 0x73, 0x2e, 0x4e, 0x85,
	0x90, 0xc3, 0xb6, 0x84, 0x50, 0xb5, 0x55, 0x30, 0xae, 0x02, 0x98, 0x24, 0x13, 0xe3, 0x62, 0x49,
	0xea, 0x89, 0xe5, 0xc2, 0x2c, 0x30, 0x00, 0x6e, 0x4f, 0x0d, 0xba, 0x12, 0x58, 0xeb, 0xe9, 0x97,
	0xb0, 0x31, 0xe6, 0xe2, 0x85, 0xcc, 0xf2, 0x0f, 0x96, 0xf5, 0x09, 0x5c, 0xb0, 0xbc, 0xf5, 0xbc,
	0x3e, 0x82, 0x1e, 0xc6, 0x31, 0x0b, 0xea, 0x49, 0x77, 0xb4, 0x61, 0x5a, 0x71, 0xca, 0x32, 0x6e,
	0x01, 0x51, 0x74, 0x29, 0x63, 0xbd, 0x86, 0x9f, 0xc0, 0x66, 0x45, 0x7a, 0x0a, 0x7b, 0xfb, 0xb0,
	0x21, 0xd9, 0xb3, 0x5d, 0xeb, 0x36, 0xe4, 0x43, 0xe8, 0xa2, 0x02, 0xd3, 0x56, 0x80, 0x29, 0x39,
	0x7d, 0x0a, 0xdd, 0x17, 0x8d, 0x9e, 0x04, 0x3a, 0xd6, 0xc1, 0xc0, 0x6f, 0x32, 0x84, 0x7e, 0xc4,
	0xf3, 0x69, 0x16, 0x2f, 0xe4, 0x91, 0x43, 0xa6, 0x3d, 0x66, 0x8b, 0x68, 0x04, 0x1d, 0x79, 0xee,
	0xfe, 0x56, 0xb4, 0x00, 0xdc, 0x38, 0x09, 0xdf, 0xf0, 0x57, 0xec, 0x89, 0x0e, 0x55, 0x8c, 0xc9,
	0x15, 0xf0, 0xa6, 0x48, 0x41, 0xb4, 0x2b, 0xfc, 0xce, 0xb0, 0x35, 0xea, 0xb0, 0x52, 0x40, 0x7f,
	0x69, 0xc1, 0xc0, 0xde, 0x90, 0xef, 0x07, 0x3c, 0xf1, 0x61, 0x05, 0x01, 0x4c, 0x22, 0x4c, 0xe9,
	0x31, 0x33, 0x24, 0x23, 0x58, 0xe7, 0x47, 0x0b, 0x9e, 0xc5, 0x3c, 0x9d, 0xf2, 0x6f, 0xc2, 0x83,
	0x19, 0xf7, 0x61, 0xd8, 0x1e, 0xb5, 0x59, 0x5d, 0x4c, 0x7f, 0x73, 0xc0, 0xdd, 0xaf, 0x9e, 0x8e,
	0xff, 0x01, 0x2c, 0x72, 0x0d, 0xba, 0xf2, 0x6a, 0xcb, 0xfd, 0xfe, 0xc9, 0x1b, 0x07, 0x2f, 0x4a,
	0xa5, 0x26, 0x57, 0xa1, 0x1b, 0x0b, 0x9e, 0xe4, 0xfe, 0x00, 0xed, 0xf0, 0x42, 0x9e, 0x08, 0x9e,
	0x30, 0x25, 0x26, 0x9f, 0xc1, 0x2a, 0xb7, 0x0e, 0x55, 0xee, 0xaf, 0x96, 0xf1, 0x2a, 0xa7, 0xad,
	0x6a, 0x46, 0xae, 0x81, 0x8b, 0x82, 0x98, 0xe7, 0xfe, 0x1a, 0xba, 0x40, 0xe9, 0xc2, 0x0a, 0x1d,
	0xfd, 0xdd, 0x81, 0x9e, 0x12, 0xbe, 0x27, 0xf2, 0xcc, 0x03, 0xd3, 0x69, 0x7c, 0x60, 0x2c, 0x6a,
	0xbb, 0x55, 0x6a, 0x6f, 0x01, 0x84, 0x42, 0x64, 0xf1, 0xc1, 0x52, 0xf0, 0xdc, 0xef, 0x21, 0xe4,
	0x55, 0xe9, 0xbd, 0x6b, 0xa4, 0xcc, 0x32, 0x90, 0x60, 0x8f, 0x16, 0xfe, 0xca, 0xb0, 0x35, 0x6a,
	0x33, 0xe7, 0x68, 0x41, 0x3e, 0x05, 0x2f, 0x4e, 0x7f, 0xe4, 0xa9, 0x98, 0x67, 0xc7, 0xbe, 0x8b,
	0xb9, 0xd1, 0x7b, 0x62, 0x84, 0xac, 0xd4, 0x13, 0x0a, 0xbd, 0x43, 0x1e, 0xce, 0xc4, 0xa1, 0xef,
	0xa1, 0x25, 0x52, 0xf3, 0x18, 0x25, 0x4c, 0x6b, 0xac, 0xfb, 0x0d, 0xce, 0xb9, 0xdf, 0xfe, 0x70,
	0x60, 0x60, 0x2b, 0xfe, 0x63, 0x22, 0xef, 0x36, 0x10, 0xb9, 0x59, 0x82, 0x6f, 0xa6, 0xb3, 0x42,
	0xdf, 0xca, 0x39, 0xf4, 0x8d, 0x0a, 0xfa, 0xdc, 0x92, 0x1a, 0x45, 0x9f, 0xa1, 0xa6, 0x20, 0x71,
	0x7d, 0x31, 0x0b, 0x8f, 0x79, 0x86, 0xd7, 0x2b, 0x9e, 0x17, 0x0f, 0x4b, 0x89, 0xba, 0x98, 0xfe,
	0xe4, 0xc0, 0x7a, 0x0d, 0x60, 0xc1, 0x5b, 0xeb, 0x74, 0xde, 0x9c, 0x33, 0x4f, 0x6f, 0xbb, 0xca,
	0x0c, 0x85, 0x41, 0xc4, 0x5f, 0x87, 0xcb, 0x99, 0xf8, 0x36, 0x9c, 0x2d, 0xb9, 0x3e, 0xdc, 0x15,
	0x99, 0xcc, 0x29, 0x8e, 0x17, 0x1c, 0x49, 0xed, 0x32, 0xfc, 0x96, 0x11, 0xe7, 0x18, 0x5b, 0xd1,
	0xe9, 0x31, 0x33, 0x94, 0x8f, 0xcc, 0x74, 0x16, 0xe6, 0x39, 0x52, 0xd6, 0x65, 0x6a, 0x20, 0xef,
	0xd9, 0xcc, 0x54, 0x4e, 0x2e, 0x4e, 0xb7, 0x18, 0xcb, 0xea, 0x2f, 0x09, 0x8f, 0x90, 0x85, 0x36,
	0x93, 0x9f, 0x28, 0x89, 0x53, 0xdc, 0x65, 0x52, 0x12, 0xa7, 0xf4, 0xe7, 0x16, 0x74, 0xe4, 0x1d,
	0xf0, 0xaf, 0x5f, 0x67, 0xd5, 0x33, 0xd7, 0x3d, 0xe7, 0xcc, 0xd1, 0x7b, 0xe0, 0x15, 0xfb, 0x81,
	0x5c, 0x37, 0x17, 0x97, 0x7a, 0x81, 0x2f, 0x54, 0x76, 0x8b, 0x75, 0x83, 0xd1, 0x09, 0xac, 0x56,
	0xe4, 0x72, 0x63, 0x4b, 0x8d, 0x5d, 0x82, 0xa2, 0x3d, 0x4a, 0x25, 0x79, 0xef, 0x96, 0x21, 0xee,
	0x04, 0x9c, 0x67, 0x9b, 0x15, 0x63, 0x3a, 0x06, 0xef, 0xec, 0xdd, 0x61, 0x56, 0xcf, 0xb1, 0x56,
	0x8f, 0x40, 0x27, 0x0a, 0x45, 0xa8, 0x99, 0xc1, 0x6f, 0xfa, 0x75, 0xf9, 0x9c, 0xe1, 0xeb, 0x79,
	0x76, 0x55, 0x2c, 0x09, 0xcc, 0x77, 0x23, 0xb9, 0x4a, 0xaa, 0x10, 0x36, 0x43, 0x7a, 0x0f, 0x06,
	0xf6, 0xbe, 0x97, 0xb9, 0x92, 0x79, 0xa4, 0x30, 0x75, 0x19, 0x7e, 0x9b, 0x15, 0x77, 0x8a, 0x15,
	0xa7, 0x7f, 0xb6, 0xa0, 0xa7, 0xdc, 0x1a, 0x1d, 0x6e, 0x40, 0x2f, 0x9d, 0x67, 0x89, 0x2e, 0x5d,
	0x34, 0xb5, 0xca, 0x7e, 0xe7, 0x19, 0x2a, 0x98, 0x36, 0x20, 0xb7, 0xc1, 0x4d, 0x96, 0x33, 0x11,
	0xef, 0x85, 0x99, 0x2e, 0xc3, 0x36, 0x2d, 0xe3, 0xa7, 0x5a, 0xc5, 0x0a, 0xa3, 0xe0, 0x31, 0xf4,
	0x54, 0x08, 0x03, 0xab, 0x55, 0x6e, 0x44, 0x1f, 0x56, 0xa6, 0xcb, 0x2c, 0xe3, 0xa9, 0xd0, 0x60,
	0xcd, 0x10, 0x69, 0xe5, 0xc9, 0x02, 0x53, 0xb4, 0x19, 0x7e, 0x07, 0xf7, 0xc1, 0x35, 0xf1, 0xa5,
	0xfe, 0x20, 0xcc, 0xd4, 0x56, 0x68, 0x33, 0xfc, 0x3e, 0x3d, 0xda, 0x9d, 0x5f, 0x7b, 0xe0, 0x3c,
	0x7c, 0x48, 0x6e, 0x40, 0x47, 0x76, 0x26, 0x64, 0x1d, 0x37, 0x5c, 0xd9, 0xc8, 0x04, 0x1b, 0xa5,
	0x40, 0x17, 0x62, 0x97, 0xc1, 0x79, 0xca, 0x09, 0xd6, 0x52, 0xd8, 0xfa, 0x04, 0xc5, 0x0a, 0x91,
	0xeb, 0xb0, 0x32, 0xe6, 0x02, 0x3f, 0x89, 0x14, 0x56, 0x9b, 0x31, 0xcb, 0xf0, 0x16, 0x40, 0xd9,
	0xa6, 0x90, 0x8b, 0xf8, 0x1e, 0xd7, 0xdb, 0x16, 0xcb, 0xfc, 0x36, 0xf4, 0xad, 0x6e, 0xa2, 0x31,
	0xf6, 0xc0, 0x7e, 0xd3, 0xc9, 0x2e, 0x0c, 0xec, 0xf6, 0x83, 0x6c, 0x6b, 0x8f, 0x7a, 0x47, 0x13,
	0xf8, 0x27, 0x15, 0x7a, 0x9a, 0x63, 0x58, 0xab, 0xb6, 0x12, 0xe4, 0x72, 0x09, 0xb3, 0xd6, 0x36,
	0x04, 0x41, 0x93, 0x4a, 0x07, 0xfa, 0x02, 0x06, 0x76, 0xa7, 0xa1, 0xb0, 0x34, 0xf4, 0x1e, 0xc1,
	0x89, 0x4e, 0x83, 0x7c, 0x0e, 0xeb, 0x63, 0x5e, 0x69, 0x10, 0x1a, 0xe7, 0x7e, 0xe2, 0x35, 0x24,
	0x0f, 0x4c, 0x65, 0x5d, 0x91, 0x5a, 0x6b, 0x76, 0xb5, 0x04, 0xdc, 0xd8, 0xab, 0xec, 0xaa, 0xea,
	0xba, 0xe2, 0xfe, 0x81, 0x01, 0xde, 0xd0, 0xb1, 0x34, 0x60, 0xb8, 0x01, 0xae, 0xe9, 0x15, 0x1a,
	0x51, 0x97, 0xd5, 0x38, 0xb9, 0x0f, 0x5e, 0xd1, 0x56, 0x90, 0x2d, 0x6d, 0x5b, 0xe9, 0x51, 0x82,
	0x8b, 0x35, 0xa9, 0xc6, 0xf9, 0x15, 0xf4, 0xad, 0x66, 0x81, 0x5c, 0x2a, 0xa7, 0x65, 0x37, 0x06,
	0xc1, 0xf6, 0x09, 0xb9, 0xf6, 0xbf, 0x09, 0x5e, 0xd1, 0x45, 0xa8, 0xcc, 0xf5, 0xa6, 0xc2, 0xc2,
	0xb9, 0xd7, 0xf9, 0xce, 0x89, 0xa2, 0x83, 0x1e, 0xfe, 0x70, 0xb8, 0xfb, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xcd, 0x4c, 0x1d, 0x41, 0x7f, 0x10, 0x00, 0x00,
}
