// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dd/dd.proto

package dd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// COMMON
type GetByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIdRequest) Reset()         { *m = GetByIdRequest{} }
func (m *GetByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetByIdRequest) ProtoMessage()    {}
func (*GetByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{0}
}
func (m *GetByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIdRequest.Unmarshal(m, b)
}
func (m *GetByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIdRequest.Marshal(b, m, deterministic)
}
func (dst *GetByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIdRequest.Merge(dst, src)
}
func (m *GetByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetByIdRequest.Size(m)
}
func (m *GetByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIdRequest proto.InternalMessageInfo

func (m *GetByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SearchParams struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchParams) Reset()         { *m = SearchParams{} }
func (m *SearchParams) String() string { return proto.CompactTextString(m) }
func (*SearchParams) ProtoMessage()    {}
func (*SearchParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{1}
}
func (m *SearchParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchParams.Unmarshal(m, b)
}
func (m *SearchParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchParams.Marshal(b, m, deterministic)
}
func (dst *SearchParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchParams.Merge(dst, src)
}
func (m *SearchParams) XXX_Size() int {
	return xxx_messageInfo_SearchParams.Size(m)
}
func (m *SearchParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchParams.DiscardUnknown(m)
}

var xxx_messageInfo_SearchParams proto.InternalMessageInfo

func (m *SearchParams) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *SearchParams) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchParams) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Blank struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blank) Reset()         { *m = Blank{} }
func (m *Blank) String() string { return proto.CompactTextString(m) }
func (*Blank) ProtoMessage()    {}
func (*Blank) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{2}
}
func (m *Blank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blank.Unmarshal(m, b)
}
func (m *Blank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blank.Marshal(b, m, deterministic)
}
func (dst *Blank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blank.Merge(dst, src)
}
func (m *Blank) XXX_Size() int {
	return xxx_messageInfo_Blank.Size(m)
}
func (m *Blank) XXX_DiscardUnknown() {
	xxx_messageInfo_Blank.DiscardUnknown(m)
}

var xxx_messageInfo_Blank proto.InternalMessageInfo

// AUTH
type AuthRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{3}
}
func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (dst *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(dst, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ReigstrationRequired bool     `protobuf:"varint,2,opt,name=reigstrationRequired,proto3" json:"reigstrationRequired,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{4}
}
func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (dst *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(dst, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AuthResponse) GetReigstrationRequired() bool {
	if m != nil {
		return m.ReigstrationRequired
	}
	return false
}

type CreateUserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{5}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// *************************************
//              CAMPAIGNS
// *************************************
type GetCampaignsRequest struct {
	Search               *SearchParams `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetCampaignsRequest) Reset()         { *m = GetCampaignsRequest{} }
func (m *GetCampaignsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCampaignsRequest) ProtoMessage()    {}
func (*GetCampaignsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{6}
}
func (m *GetCampaignsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCampaignsRequest.Unmarshal(m, b)
}
func (m *GetCampaignsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCampaignsRequest.Marshal(b, m, deterministic)
}
func (dst *GetCampaignsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCampaignsRequest.Merge(dst, src)
}
func (m *GetCampaignsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCampaignsRequest.Size(m)
}
func (m *GetCampaignsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCampaignsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCampaignsRequest proto.InternalMessageInfo

func (m *GetCampaignsRequest) GetSearch() *SearchParams {
	if m != nil {
		return m.Search
	}
	return nil
}

type GetCampaignsResponse struct {
	Campaigns            []*CampaignCore `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	Total                uint32          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetCampaignsResponse) Reset()         { *m = GetCampaignsResponse{} }
func (m *GetCampaignsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCampaignsResponse) ProtoMessage()    {}
func (*GetCampaignsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{7}
}
func (m *GetCampaignsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCampaignsResponse.Unmarshal(m, b)
}
func (m *GetCampaignsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCampaignsResponse.Marshal(b, m, deterministic)
}
func (dst *GetCampaignsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCampaignsResponse.Merge(dst, src)
}
func (m *GetCampaignsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCampaignsResponse.Size(m)
}
func (m *GetCampaignsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCampaignsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCampaignsResponse proto.InternalMessageInfo

func (m *GetCampaignsResponse) GetCampaigns() []*CampaignCore {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

func (m *GetCampaignsResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CreateCampaignRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCampaignRequest) Reset()         { *m = CreateCampaignRequest{} }
func (m *CreateCampaignRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCampaignRequest) ProtoMessage()    {}
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{8}
}
func (m *CreateCampaignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCampaignRequest.Unmarshal(m, b)
}
func (m *CreateCampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCampaignRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCampaignRequest.Merge(dst, src)
}
func (m *CreateCampaignRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCampaignRequest.Size(m)
}
func (m *CreateCampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCampaignRequest proto.InternalMessageInfo

type CreateCampaignResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCampaignResponse) Reset()         { *m = CreateCampaignResponse{} }
func (m *CreateCampaignResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCampaignResponse) ProtoMessage()    {}
func (*CreateCampaignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{9}
}
func (m *CreateCampaignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCampaignResponse.Unmarshal(m, b)
}
func (m *CreateCampaignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCampaignResponse.Marshal(b, m, deterministic)
}
func (dst *CreateCampaignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCampaignResponse.Merge(dst, src)
}
func (m *CreateCampaignResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCampaignResponse.Size(m)
}
func (m *CreateCampaignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCampaignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCampaignResponse proto.InternalMessageInfo

func (m *CreateCampaignResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EditCampaignRequest struct {
	Campaign             *CampaignCore `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	Id                   string        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EditCampaignRequest) Reset()         { *m = EditCampaignRequest{} }
func (m *EditCampaignRequest) String() string { return proto.CompactTextString(m) }
func (*EditCampaignRequest) ProtoMessage()    {}
func (*EditCampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{10}
}
func (m *EditCampaignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditCampaignRequest.Unmarshal(m, b)
}
func (m *EditCampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditCampaignRequest.Marshal(b, m, deterministic)
}
func (dst *EditCampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditCampaignRequest.Merge(dst, src)
}
func (m *EditCampaignRequest) XXX_Size() int {
	return xxx_messageInfo_EditCampaignRequest.Size(m)
}
func (m *EditCampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditCampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditCampaignRequest proto.InternalMessageInfo

func (m *EditCampaignRequest) GetCampaign() *CampaignCore {
	if m != nil {
		return m.Campaign
	}
	return nil
}

func (m *EditCampaignRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetQuestsRequest struct {
	Search               *SearchParams `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetQuestsRequest) Reset()         { *m = GetQuestsRequest{} }
func (m *GetQuestsRequest) String() string { return proto.CompactTextString(m) }
func (*GetQuestsRequest) ProtoMessage()    {}
func (*GetQuestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{11}
}
func (m *GetQuestsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuestsRequest.Unmarshal(m, b)
}
func (m *GetQuestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuestsRequest.Marshal(b, m, deterministic)
}
func (dst *GetQuestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuestsRequest.Merge(dst, src)
}
func (m *GetQuestsRequest) XXX_Size() int {
	return xxx_messageInfo_GetQuestsRequest.Size(m)
}
func (m *GetQuestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuestsRequest proto.InternalMessageInfo

func (m *GetQuestsRequest) GetSearch() *SearchParams {
	if m != nil {
		return m.Search
	}
	return nil
}

type GetQuestsResponse struct {
	Quests               []*Quest `protobuf:"bytes,1,rep,name=quests,proto3" json:"quests,omitempty"`
	Total                uint32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuestsResponse) Reset()         { *m = GetQuestsResponse{} }
func (m *GetQuestsResponse) String() string { return proto.CompactTextString(m) }
func (*GetQuestsResponse) ProtoMessage()    {}
func (*GetQuestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{12}
}
func (m *GetQuestsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuestsResponse.Unmarshal(m, b)
}
func (m *GetQuestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuestsResponse.Marshal(b, m, deterministic)
}
func (dst *GetQuestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuestsResponse.Merge(dst, src)
}
func (m *GetQuestsResponse) XXX_Size() int {
	return xxx_messageInfo_GetQuestsResponse.Size(m)
}
func (m *GetQuestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuestsResponse proto.InternalMessageInfo

func (m *GetQuestsResponse) GetQuests() []*Quest {
	if m != nil {
		return m.Quests
	}
	return nil
}

func (m *GetQuestsResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CreateQuestRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateQuestRequest) Reset()         { *m = CreateQuestRequest{} }
func (m *CreateQuestRequest) String() string { return proto.CompactTextString(m) }
func (*CreateQuestRequest) ProtoMessage()    {}
func (*CreateQuestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{13}
}
func (m *CreateQuestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQuestRequest.Unmarshal(m, b)
}
func (m *CreateQuestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQuestRequest.Marshal(b, m, deterministic)
}
func (dst *CreateQuestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQuestRequest.Merge(dst, src)
}
func (m *CreateQuestRequest) XXX_Size() int {
	return xxx_messageInfo_CreateQuestRequest.Size(m)
}
func (m *CreateQuestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQuestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQuestRequest proto.InternalMessageInfo

type CreateQuestResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateQuestResponse) Reset()         { *m = CreateQuestResponse{} }
func (m *CreateQuestResponse) String() string { return proto.CompactTextString(m) }
func (*CreateQuestResponse) ProtoMessage()    {}
func (*CreateQuestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{14}
}
func (m *CreateQuestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQuestResponse.Unmarshal(m, b)
}
func (m *CreateQuestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQuestResponse.Marshal(b, m, deterministic)
}
func (dst *CreateQuestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQuestResponse.Merge(dst, src)
}
func (m *CreateQuestResponse) XXX_Size() int {
	return xxx_messageInfo_CreateQuestResponse.Size(m)
}
func (m *CreateQuestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQuestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQuestResponse proto.InternalMessageInfo

func (m *CreateQuestResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EditQuestRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quest                *Quest   `protobuf:"bytes,2,opt,name=quest,proto3" json:"quest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditQuestRequest) Reset()         { *m = EditQuestRequest{} }
func (m *EditQuestRequest) String() string { return proto.CompactTextString(m) }
func (*EditQuestRequest) ProtoMessage()    {}
func (*EditQuestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{15}
}
func (m *EditQuestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditQuestRequest.Unmarshal(m, b)
}
func (m *EditQuestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditQuestRequest.Marshal(b, m, deterministic)
}
func (dst *EditQuestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditQuestRequest.Merge(dst, src)
}
func (m *EditQuestRequest) XXX_Size() int {
	return xxx_messageInfo_EditQuestRequest.Size(m)
}
func (m *EditQuestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditQuestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditQuestRequest proto.InternalMessageInfo

func (m *EditQuestRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EditQuestRequest) GetQuest() *Quest {
	if m != nil {
		return m.Quest
	}
	return nil
}

type Quest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quest) Reset()         { *m = Quest{} }
func (m *Quest) String() string { return proto.CompactTextString(m) }
func (*Quest) ProtoMessage()    {}
func (*Quest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{16}
}
func (m *Quest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quest.Unmarshal(m, b)
}
func (m *Quest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quest.Marshal(b, m, deterministic)
}
func (dst *Quest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quest.Merge(dst, src)
}
func (m *Quest) XXX_Size() int {
	return xxx_messageInfo_Quest.Size(m)
}
func (m *Quest) XXX_DiscardUnknown() {
	xxx_messageInfo_Quest.DiscardUnknown(m)
}

var xxx_messageInfo_Quest proto.InternalMessageInfo

func (m *Quest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Quest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Quest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageURL             string   `protobuf:"bytes,3,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	CreatedAt            uint64   `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{17}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

func (m *User) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type CampaignCore struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageId              string   `protobuf:"bytes,4,opt,name=imageId,proto3" json:"imageId,omitempty"`
	ExperienceTable      []uint64 `protobuf:"varint,10,rep,packed,name=experienceTable,proto3" json:"experienceTable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CampaignCore) Reset()         { *m = CampaignCore{} }
func (m *CampaignCore) String() string { return proto.CompactTextString(m) }
func (*CampaignCore) ProtoMessage()    {}
func (*CampaignCore) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{18}
}
func (m *CampaignCore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignCore.Unmarshal(m, b)
}
func (m *CampaignCore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignCore.Marshal(b, m, deterministic)
}
func (dst *CampaignCore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignCore.Merge(dst, src)
}
func (m *CampaignCore) XXX_Size() int {
	return xxx_messageInfo_CampaignCore.Size(m)
}
func (m *CampaignCore) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignCore.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignCore proto.InternalMessageInfo

func (m *CampaignCore) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CampaignCore) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CampaignCore) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CampaignCore) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *CampaignCore) GetExperienceTable() []uint64 {
	if m != nil {
		return m.ExperienceTable
	}
	return nil
}

type Campaign struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageId              string   `protobuf:"bytes,4,opt,name=imageId,proto3" json:"imageId,omitempty"`
	ExperienceTable      []uint64 `protobuf:"varint,10,rep,packed,name=experienceTable,proto3" json:"experienceTable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Campaign) Reset()         { *m = Campaign{} }
func (m *Campaign) String() string { return proto.CompactTextString(m) }
func (*Campaign) ProtoMessage()    {}
func (*Campaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd_050615c3e76ef901, []int{19}
}
func (m *Campaign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Campaign.Unmarshal(m, b)
}
func (m *Campaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Campaign.Marshal(b, m, deterministic)
}
func (dst *Campaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Campaign.Merge(dst, src)
}
func (m *Campaign) XXX_Size() int {
	return xxx_messageInfo_Campaign.Size(m)
}
func (m *Campaign) XXX_DiscardUnknown() {
	xxx_messageInfo_Campaign.DiscardUnknown(m)
}

var xxx_messageInfo_Campaign proto.InternalMessageInfo

func (m *Campaign) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Campaign) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Campaign) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Campaign) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *Campaign) GetExperienceTable() []uint64 {
	if m != nil {
		return m.ExperienceTable
	}
	return nil
}

func init() {
	proto.RegisterType((*GetByIdRequest)(nil), "dd.GetByIdRequest")
	proto.RegisterType((*SearchParams)(nil), "dd.SearchParams")
	proto.RegisterType((*Blank)(nil), "dd.Blank")
	proto.RegisterType((*AuthRequest)(nil), "dd.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "dd.AuthResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "dd.CreateUserRequest")
	proto.RegisterType((*GetCampaignsRequest)(nil), "dd.GetCampaignsRequest")
	proto.RegisterType((*GetCampaignsResponse)(nil), "dd.GetCampaignsResponse")
	proto.RegisterType((*CreateCampaignRequest)(nil), "dd.CreateCampaignRequest")
	proto.RegisterType((*CreateCampaignResponse)(nil), "dd.CreateCampaignResponse")
	proto.RegisterType((*EditCampaignRequest)(nil), "dd.EditCampaignRequest")
	proto.RegisterType((*GetQuestsRequest)(nil), "dd.GetQuestsRequest")
	proto.RegisterType((*GetQuestsResponse)(nil), "dd.GetQuestsResponse")
	proto.RegisterType((*CreateQuestRequest)(nil), "dd.CreateQuestRequest")
	proto.RegisterType((*CreateQuestResponse)(nil), "dd.CreateQuestResponse")
	proto.RegisterType((*EditQuestRequest)(nil), "dd.EditQuestRequest")
	proto.RegisterType((*Quest)(nil), "dd.Quest")
	proto.RegisterType((*User)(nil), "dd.User")
	proto.RegisterType((*CampaignCore)(nil), "dd.CampaignCore")
	proto.RegisterType((*Campaign)(nil), "dd.Campaign")
}

func init() { proto.RegisterFile("dd/dd.proto", fileDescriptor_dd_050615c3e76ef901) }

var fileDescriptor_dd_050615c3e76ef901 = []byte{
	// 738 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0x56, 0x1c, 0x27, 0xc4, 0x93, 0x1c, 0x08, 0x43, 0x00, 0x63, 0x21, 0x1d, 0x9f, 0x3d, 0x3a,
	0x3a, 0x46, 0xa2, 0x41, 0xa2, 0x37, 0xad, 0x54, 0xb5, 0x82, 0x80, 0x22, 0x24, 0xa8, 0xca, 0x52,
	0x6e, 0xaa, 0x5e, 0xd4, 0x64, 0x17, 0xb0, 0x48, 0xec, 0xd4, 0x5e, 0xa4, 0xf6, 0x3d, 0x7a, 0xd1,
	0x97, 0xec, 0x3b, 0x54, 0x5e, 0xaf, 0xed, 0xb5, 0x09, 0x55, 0x55, 0xf5, 0xa2, 0x77, 0x9e, 0xbf,
	0x6f, 0xbe, 0x99, 0xcc, 0x7e, 0x81, 0x2e, 0x63, 0x7b, 0x8c, 0x0d, 0xe7, 0x71, 0x24, 0x22, 0x34,
	0x18, 0x23, 0x2e, 0x2c, 0x8f, 0xb9, 0x38, 0xfc, 0x7c, 0xc2, 0x28, 0xff, 0x78, 0xcf, 0x13, 0x81,
	0xcb, 0x60, 0x04, 0xcc, 0x6e, 0xb8, 0x0d, 0xcf, 0xa2, 0x46, 0xc0, 0xc8, 0x6b, 0xe8, 0x5d, 0x70,
	0x3f, 0x9e, 0xdc, 0xbe, 0xf1, 0x63, 0x7f, 0x96, 0x60, 0x1f, 0x9a, 0x01, 0x4b, 0xec, 0x86, 0xdb,
	0xf4, 0x2c, 0x9a, 0x7e, 0xe2, 0x00, 0x5a, 0xd3, 0x60, 0x16, 0x08, 0xdb, 0x70, 0x1b, 0xde, 0x5f,
	0x34, 0x33, 0x70, 0x03, 0xda, 0xd1, 0xf5, 0x75, 0xc2, 0x85, 0xdd, 0x94, 0x6e, 0x65, 0x91, 0x25,
	0x68, 0x1d, 0x4e, 0xfd, 0xf0, 0x8e, 0xfc, 0x0b, 0xdd, 0x83, 0x7b, 0x71, 0x9b, 0xf7, 0x1d, 0x40,
	0x4b, 0x44, 0x77, 0x3c, 0x54, 0xad, 0x33, 0x83, 0x7c, 0x80, 0x5e, 0x96, 0x94, 0xcc, 0xa3, 0x30,
	0xe1, 0xb8, 0x0d, 0xe6, 0x7d, 0xc2, 0x63, 0x99, 0xd4, 0xdd, 0xef, 0x0c, 0x19, 0x1b, 0x5e, 0x26,
	0x3c, 0xa6, 0xd2, 0x8b, 0xfb, 0x30, 0x88, 0x79, 0x70, 0x93, 0x88, 0xd8, 0x17, 0x41, 0x14, 0xa6,
	0xd0, 0x41, 0xcc, 0x99, 0x24, 0xd6, 0xa1, 0x0b, 0x63, 0xe4, 0x18, 0x56, 0x47, 0x31, 0xf7, 0x05,
	0x97, 0x38, 0x3f, 0x22, 0x83, 0x0e, 0x74, 0xd2, 0x36, 0xa1, 0x3f, 0xe3, 0x12, 0xd2, 0xa2, 0x85,
	0x4d, 0x5e, 0xc1, 0xda, 0x98, 0x8b, 0x91, 0x3f, 0x9b, 0xfb, 0xc1, 0x4d, 0x98, 0xe4, 0x40, 0x1e,
	0xb4, 0x13, 0xb9, 0x3d, 0xc5, 0xb8, 0x9f, 0x32, 0xd6, 0xf7, 0x49, 0x55, 0x9c, 0xbc, 0x87, 0x41,
	0x15, 0x40, 0x4d, 0x3c, 0x04, 0x6b, 0x92, 0x3b, 0xe5, 0xd6, 0x15, 0x48, 0x9e, 0x39, 0x8a, 0x62,
	0x4e, 0xcb, 0x94, 0x8c, 0xba, 0xf0, 0xa7, 0xf9, 0xaf, 0x21, 0x0d, 0xb2, 0x09, 0xeb, 0xd9, 0x94,
	0x79, 0x99, 0x22, 0x48, 0x3c, 0xd8, 0xa8, 0x07, 0x54, 0xe3, 0xfa, 0x21, 0x5c, 0xc0, 0xda, 0x31,
	0x0b, 0x44, 0x0d, 0x00, 0x77, 0xa1, 0x93, 0x37, 0xd7, 0x67, 0xac, 0xd0, 0x2b, 0x32, 0x14, 0xa8,
	0x51, 0x80, 0xbe, 0x80, 0xfe, 0x98, 0x8b, 0xf3, 0x14, 0xe9, 0x17, 0x76, 0x76, 0x0a, 0xab, 0x5a,
	0xb5, 0xe2, 0xfd, 0x0f, 0xb4, 0x25, 0x4e, 0xbe, 0x2d, 0x2b, 0x2d, 0x97, 0x39, 0x54, 0x05, 0x1e,
	0xd9, 0xd1, 0x00, 0x30, 0x5b, 0x45, 0x96, 0xac, 0x16, 0xf4, 0x1f, 0xac, 0x55, 0xbc, 0x8f, 0x6c,
	0x67, 0x04, 0xfd, 0x74, 0x3b, 0x7a, 0x69, 0x3d, 0x07, 0xff, 0x86, 0x96, 0x0c, 0xc8, 0xb6, 0x15,
	0x62, 0x99, 0x9f, 0x9c, 0x41, 0xeb, 0x7c, 0x61, 0x25, 0x82, 0xa9, 0x5d, 0x9d, 0xfc, 0x46, 0x17,
	0xba, 0x8c, 0x27, 0x93, 0x38, 0x98, 0xa7, 0xf7, 0x2c, 0x5f, 0x99, 0x45, 0x75, 0x17, 0x61, 0x60,
	0xa6, 0x47, 0xfd, 0x53, 0x68, 0x0e, 0x74, 0x82, 0x99, 0x7f, 0xc3, 0x2f, 0xe9, 0xa9, 0x82, 0x2a,
	0x6c, 0xdc, 0x06, 0x6b, 0x22, 0x57, 0xc0, 0x0e, 0x84, 0x6d, 0xba, 0x0d, 0xcf, 0xa4, 0xa5, 0x83,
	0x7c, 0x6d, 0x40, 0x4f, 0xff, 0xb5, 0x7f, 0x0f, 0x79, 0xb4, 0x61, 0x49, 0x12, 0x38, 0x61, 0xb2,
	0xa5, 0x45, 0x73, 0x13, 0x3d, 0x58, 0xe1, 0x9f, 0xe6, 0x3c, 0x0e, 0x78, 0x38, 0xe1, 0x6f, 0xfd,
	0xab, 0x29, 0xb7, 0xc1, 0x6d, 0x7a, 0x26, 0xad, 0xbb, 0xc9, 0x97, 0x06, 0x74, 0x46, 0xd5, 0xd3,
	0xfb, 0x03, 0x68, 0xed, 0x7f, 0x33, 0xc1, 0x38, 0x3a, 0xc2, 0x1d, 0x30, 0x53, 0x6d, 0xc3, 0x95,
	0xf4, 0x0e, 0x34, 0x29, 0x74, 0xfa, 0xa5, 0x43, 0x5d, 0xdb, 0x16, 0x18, 0x67, 0x1c, 0xe5, 0xc1,
	0x48, 0xf1, 0x74, 0x0a, 0xe5, 0xc3, 0xff, 0x61, 0x69, 0xcc, 0x85, 0xfc, 0xc4, 0xd4, 0x59, 0x95,
	0x73, 0x2d, 0xf1, 0x09, 0x40, 0x29, 0x74, 0xb8, 0x2e, 0x1f, 0x69, 0x5d, 0xf8, 0xb4, 0xf4, 0x3d,
	0xe8, 0x6a, 0x7a, 0xb4, 0x10, 0xbb, 0xa7, 0x3f, 0x74, 0x3c, 0x80, 0x9e, 0x2e, 0x60, 0xb8, 0xa9,
	0x2a, 0xea, 0x9a, 0xe8, 0xd8, 0x0f, 0x03, 0x6a, 0xcc, 0x31, 0x2c, 0x57, 0xc5, 0x08, 0xb7, 0x4a,
	0x9a, 0x35, 0xe1, 0x71, 0x9c, 0x45, 0x21, 0x05, 0xf4, 0x1c, 0x7a, 0xba, 0x56, 0x65, 0x5c, 0x16,
	0xa8, 0x97, 0xf3, 0x40, 0xab, 0x70, 0x07, 0x3a, 0xb9, 0xa6, 0x2c, 0x1c, 0xba, 0x7c, 0xb5, 0xf8,
	0x0c, 0xac, 0x42, 0x7e, 0x70, 0xa0, 0x72, 0x2b, 0x5a, 0xe6, 0xac, 0xd7, 0xbc, 0x8a, 0xdf, 0x4b,
	0xe8, 0x6a, 0xa2, 0x82, 0x1b, 0xe5, 0x28, 0xba, 0x80, 0x38, 0x9b, 0x0f, 0xfc, 0xaa, 0x7e, 0x17,
	0xac, 0x42, 0x6d, 0xb2, 0xce, 0x75, 0xf1, 0xd1, 0x78, 0x1e, 0x9a, 0xef, 0x0c, 0xc6, 0xae, 0xda,
	0xf2, 0x5f, 0xff, 0xe9, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x59, 0x28, 0xa8, 0x04, 0x08,
	0x00, 0x00,
}
