import { EntityAttributeClass, IEntityFieldConfig } from './entity.service';
import { DynamicFieldType } from './custom-controls/dynform/form-types';

export const DND_5E: IEntityFieldConfig[] = [
  {
    name: 'AC',
    description: 'Armor Class',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MAJOR,
    options: { required: true },
  },
  {
    name: 'Init',
    description: 'Initiative',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MAJOR,
    options: { required: true },
  },
  {
    name: 'Speed',
    description: 'Speed',
    type: DynamicFieldType.STRING,
    class: EntityAttributeClass.MAJOR,
    options: { required: true },
  },
  {
    name: 'Class',
    description: 'Class',
    type: DynamicFieldType.ENUM_MULTI,
    class: EntityAttributeClass.NORMAL,
    options: {
      required: true,
      choices: ['Barbarian', 'Bard', 'Cleric', 'Druid', 'Fighter', 'Paladin', 'Ranger', 'Rogue', 'Sorcerer', 'Warlock', 'Wizard'],
    },
  },
  {
    name: 'Strength',
    description: 'Strength',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.NORMAL,
    options: { required: true },
  },
  {
    name: 'Strength Mod',
    description: 'Strength Modifier',
    type: DynamicFieldType.STRING,
    class: EntityAttributeClass.NORMAL,
    options: { required: false, modifierFor: 'Strength' },
  },
  {
    name: 'Dexterity',
    description: 'Dexterity',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.NORMAL,
    options: { required: true },
  },
  {
    name: 'Dex Mod',
    description: 'Dexterity Modifier',
    type: DynamicFieldType.STRING,
    class: EntityAttributeClass.NORMAL,
    options: { required: false, modifierFor: 'Dexterity' },
  },
  {
    name: 'Constitution',
    description: 'Constitution',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.NORMAL,
    options: { required: true },
  },
  {
    name: 'Con Mod',
    description: 'Constitution Modifier',
    type: DynamicFieldType.STRING,
    class: EntityAttributeClass.NORMAL,
    options: { required: false, modifierFor: 'Constitution' },
  },
  {
    name: 'Intelligence',
    description: 'Intelligence',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.NORMAL,
    options: { required: true },
  },
  {
    name: 'Int Mod',
    description: 'Intelligence Modifier',
    type: DynamicFieldType.STRING,
    class: EntityAttributeClass.NORMAL,
    options: { required: false, modifierFor: 'Intelligence' },
  },
  {
    name: 'Wisdom',
    description: 'Wisdom',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.NORMAL,
    options: { required: true },
  },
  {
    name: 'Wis Mod',
    description: 'Wisdom Modifier',
    type: DynamicFieldType.STRING,
    class: EntityAttributeClass.NORMAL,
    options: { required: false, modifierFor: 'Wisdom' },
  },
  {
    name: 'Charisma',
    description: 'Charisma',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.NORMAL,
    options: { required: true },
  },
  {
    name: 'Cha Mod',
    description: 'Charisma Modifier',
    type: DynamicFieldType.STRING,
    class: EntityAttributeClass.NORMAL,
    options: { required: false, modifierFor: 'Charisma' },
  },
  {
    name: 'Acrobatics',
    description: 'Acrobatics',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Animal Handling',
    description: 'Animal Handling',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Arcana',
    description: 'Arcana',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Athletics',
    description: 'Athletics',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Deception',
    description: 'Deception',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'History',
    description: 'History',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Insight',
    description: 'Insight',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Intimidation',
    description: 'Intimidation',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Investigation',
    description: 'Investigation',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Medicine',
    description: 'Medicine',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Nature',
    description: 'Nature',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Perception',
    description: 'Perception',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Performance',
    description: 'Performance',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Persuasion',
    description: 'Persuasion',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Religion',
    description: 'Religion',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Sleight of Hand',
    description: 'Sleight of Hand',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Stealth',
    description: 'Stealth',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Survival',
    description: 'Survival',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Alignment',
    description: 'Alignment',
    type: DynamicFieldType.STRING,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Race',
    description: 'Race',
    type: DynamicFieldType.ENUM,
    class: EntityAttributeClass.MINOR,
    options: {
      required: false,
      choices: ['Dragonborn', 'Dwarf', 'Eladrin', 'Elf', 'Gnome', 'Half-elf', 'Half-orc', 'Halfling', 'Human', 'Tiefling'],
    },
  },
  {
    name: 'Age',
    description: 'Age',
    type: DynamicFieldType.INT,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Height',
    description: 'Height',
    type: DynamicFieldType.STRING,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Weight',
    description: 'Weight',
    type: DynamicFieldType.STRING,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Eyes',
    description: 'Eyes',
    type: DynamicFieldType.STRING,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Skin',
    description: 'Skin',
    type: DynamicFieldType.STRING,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Hair',
    description: 'Hair',
    type: DynamicFieldType.STRING,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Allies & Orgs',
    description: 'Allies & Organizations',
    type: DynamicFieldType.TEXT_FORMATTED,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Features & Traits',
    description: 'Features & Traits',
    type: DynamicFieldType.TEXT_FORMATTED,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
  {
    name: 'Backstory',
    description: 'Backstory',
    type: DynamicFieldType.TEXT_FORMATTED,
    class: EntityAttributeClass.MINOR,
    options: { required: false },
  },
];
